name: DevCycle Feature Flag Code Usages
description: Identifies DevCycle variable references within your project, and populates Code Usages in your DevCycle dashboard.
author: DevCycleHQ
inputs:
  project-key:
    description: "Your DevCycle project key (Recommended)"
    required: false
  client-id:
    description: "Your DevCycle API client ID (Recommended)"
    required: false
  client-secret:
    description: "Your DevCycle API client secret (Recommended)"
    required: false
  github-token:
    description: "The GitHub token for your repo"
    required: true
runs:
  using: node20
  main: dist/index.js
