name: Unit Tests
permissions:
  contents: read

on: pull_request

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - uses: actions/setup-node@v7
        with:
          node-version: 24
      - run: corepack enable && yarn --version
      - run: yarn install
      - run: yarn test
